# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 47181a5cbc8b4508af25a712b300aa63d2be72f8

{
  "title": "Стул IKEA",
  "description": "Срочно"
}


###

# удаление объявления
DELETE {{baseUrl}}/advertisements/4/
Content-Type: application/json
Authorization: Token 47181a5cbc8b4508af25a712b300aa63d2be72f8

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/3/
Content-Type: application/json
Authorization: Token 47181a5cbc8b4508af25a712b300aa63d2be72f8

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2020-07-06
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json

###
